In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests
%matplotlib inline
import csv
import os

In [106]:
#Enter the user profile below

Userlink = 'https://www.airbnb.com/users/show/99824610'

#Enter Number of listings

listings = 200

In [107]:

def get_page(url):
    response = requests.get(url)
    
    if not response.ok:
        print('Server responded:', response.status_code)
    else:
        soup = BeautifulSoup(response.text, 'lxml')
    return soup




def get_detail_data(soup, l):
    
    try:
        h1 = soup.find(id,'_pog3hg')
        h2 = soup.find(id,'_1b3ij9t')
        
        reviews=h1.text
        reviews=reviews.split(' ', 1)[0]
        
        name=h2.text
        name=name.rsplit(None, 1)[-1]
        
        data = {
         'Name': name,
         'Reviews': reviews
        }
        
        return data
    
    except:
        1       
        
        
      
    
        
def get_index_data(soup):
    try:
        links = soup.find_all('a','_gjfol0')
    except:
        links = []
    urls = [item.get('href') for item in links]
    return urls





def write_csv(data, url):
    with open('output.csv','a') as csvfile:
        writer = csv.writer(csvfile)
        row = [data['Name'],data['Reviews'],'https://www.airbnb.com.au/'+url]
        writer.writerow(row)
        
        
        


rows_list=[]
def main():
    
    for pg in range(0,listings,20):
        url = 'https://www.airbnb.com.au/s/Melbourne--Australia/homes?&place_id=ChIJgf0RD69C1moR4OeMIXVWBAU&items_offset='+str(pg)
        products = get_index_data(get_page(url))
        for link in products:
            data = get_detail_data(get_page('https://www.airbnb.com.au/'+link),'https://www.airbnb.com.au/'+link)
            if not data == None:
                rows_list.append(data)
                #write_csv(data, link)
            else:
                1
    
    df = pd.DataFrame(rows_list)
    df = df.drop_duplicates(keep='last')
    return df

df = main()

In [108]:
rows_list=[]
def input(soup, l):   
    try:
        h1 = soup.find(id,'_1ekkhy94')
        h2 = soup.find('h2',id = 'review-section-title')
        
        reviews=h2.text
        reviews=reviews.split(' ', 1)[0]
        
        name=h1.text
        name=name.rsplit(None, 1)[-1]
        
        data = {
         'Name': name,
         'Reviews': reviews
        }
        rows_list.append(data)
    
    except:
        1
    
    i = pd.DataFrame(rows_list)
    i = i.drop_duplicates(keep='last')
    return i





i=input(get_page(Userlink), Userlink)
mt = pd.concat([df, i], ignore_index=True)
mt = mt[mt.Reviews.apply(lambda x: x.isnumeric())]
mt['Reviews'] = pd.to_numeric(mt['Reviews'])
mt= mt.sort_values('Reviews',ascending=True)
mt['Percentile_rank']=100 - mt['Reviews'].rank(pct=True)*100
i_Name = i['Name'].to_string(index=False).replace(' ','')
i = mt.loc[mt['Name'] == i_Name]
i_rank = (i['Percentile_rank']).to_string(index=False).replace(' ','')






print(' ')
print('-------------User',i_Name,'is in the top',i_rank,'%','of Melbourne Airbnb users based on number of reviews-------------')
print('\n\n\n')
print('Details of All Melbourne Users who provide services in the first 10 pages - ','Total: ',mt.shape[0],'users')
print('\n')
print(mt)

-------------User Dee is in the top 96.666667 % of Melbourne Airbnb users based on number of reviews-------------




Details of All Melbourne Users who provide services in the first 10 pages -  Total:  60 users


             Name  Reviews  Percentile_rank
56         Studio       13        98.333333
59            Dee       15        96.666667
33            Jie       34        95.000000
23         Mohsen       38        92.500000
26            Lfs       38        92.500000
9          Ailing       72        90.000000
31        Vincent       83        88.333333
52           Stig       91        86.666667
47          Hasan       95        85.000000
14       Grantley       97        83.333333
53           Ares      111        81.666667
25          Kenny      114        80.000000
30            Rob      126        78.333333
4           Chris      127        76.666667
49      Melbourne      171        75.000000
46         Lorena      181        73.333333
1             Nan      183        71.666667
20            Jin      195        70.000000
17         Andres      204        68.333333
0            Hadi      212        66.666667
28        Bronwyn      223        65.000000
13          Homie      227        63.333333
7            Coco      244        61.666667
36        Michael      271        60.000000
29           Anna      278        58.333333
3            Leng      289        56.666667
2         Kenneth      302        55.000000
57          David      322        53.333333
12        Charlee      336        51.666667
8            Sean      358        50.000000
10          Gabby      364        48.333333
27            Sam      365        46.666667
16        Hosting      429        45.000000
38        Susanna      433        43.333333
11              J      497        41.666667
55       Mengyang      551        40.000000
58         Jeremy      558        38.333333
48         Justin      591        36.666667
32        Junling      638        35.000000
45           Anna      674        33.333333
37           Beau      721        31.666667
44          David      727        30.000000
21           Tony      815        28.333333
39            S&J      842        26.666667
34           Ivan      966        25.000000
22         Ramona     1105        23.333333
51           Alex     1177        21.666667
40         Claire     1573        20.000000
24           Yong     1662        18.333333
19          James     1888        16.666667
18          Dilin     2035        15.000000
6            Cozy     2518        13.333333
35         Chammy     2562        11.666667
54         (Bill)     3057        10.000000
42  Canvas-Suites     3272         8.333333
41            S&S     4360         6.666667
50              6     5771         5.000000
5       Apartment     7343         3.333333
43           Paul     9621         1.666667
15            SSP    27961         0.000000